#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#    controller: App\Controller\DefaultController::index
app_form:
  path: /addDestination
  controller:
    App\Controller\DestinationController::avecJQuery
